apiVersion: v1
kind: Service
metadata:
  name: pgbench-ux-service
  namespace: postgres-performance
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer