name: Build and Push Docker Image to ghcr

on:
  workflow_dispatch:
      
jobs:
  
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: 'Build Inventory Image'
        working-directory: ./app
        run: |
          docker build . --tag ghcr.io/willschipp/pgbench-ui:latest
          docker push ghcr.io/willschipp/pgbench-ui:latest